# a database.yml that takes its values from environment variables
#

default: &default
  url: <%= ENV.fetch('DATABASE_URL') %>
  encoding: unicode
  pool: 5

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
